project:
  type: website

website:
  title: "HOXO-M Blog"
  site-url: https://hoxo-m.github.io/blog/
  description: "Insights into R and Data Analysis"
  margin-header: sidebar.html
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/hoxo-m/
      # - icon: bluesky
      #   href: https://bsky.app/profile/hoxo-m.bsky.social
      - icon: rss-fill
        href: index.xml
  google-analytics:
    tracking-id: "G-RDZMKR8HFQ"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: light
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
