project:
  type: website

website:
  title: "HOXO-M Blog"
  site-url: https://hoxo-m.github.io/blog/
  description: "Insights into R and Data Analysis"
  margin-header: sidebar.html
  navbar:
    right:
#      - about.qmd
      - icon: github
        href: https://github.com/hoxo-m/
      - icon: rss-fill
        href: index.xml
#      - icon: twitter
#        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
